name: Create and upload release on tag

on:
  push:
    tags:
      - "*"  # Runs for any tag

env:
  REGISTRY: ghcr.io
  ARTIFACT_PREFIX: uki-

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}

      - name: Install ORAS
        uses: oras-project/setup-oras@v1

      - name: Authenticate ORAS
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $PASSWORD | oras login -u $USERNAME --password-stdin $REGISTRY

      - name: Compress And Push Artifacts
        env:
          ARTIFACT_REPO: "${{ env.REGISTRY }}/${{ github.repository }}/${{ env.ARTIFACT_PREFIX }}${{ github.event.repository.name }}"
          ARTIFACT_VERSION: ${{ github.ref_name }}
        run: |
          tar  --exclude='**/.git' -czf ${{ github.event.repository.name }}-${ARTIFACT_VERSION}.tar.gz ${{ github.event.repository.name }}
          EXTRA_TAGS=""
          if [[ "$ARTIFACT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            EXTRA_TAGS=",latest"
          fi
          oras push \
            --annotation "org.opencontainers.image.title=${{ env.ARTIFACT_PREFIX }}${{github.event.repository.name}} ${ARTIFACT_VERSION}" \
            --annotation "org.opencontainers.image.ref.name=${{ env.ARTIFACT_PREFIX }}${{github.event.repository.name}}:${ARTIFACT_VERSION}" \
            --annotation "org.opencontainers.image.version=${ARTIFACT_VERSION}" \
            --annotation "org.opencontainers.image.source=github.com/${{ github.repository }}" \
            --annotation "org.opencontainers.image.revision=${{ github.sha }}" \
            ${ARTIFACT_REPO}:${ARTIFACT_VERSION}${EXTRA_TAGS} \
            ${{ github.event.repository.name }}-${ARTIFACT_VERSION}.tar.gz

